In [1]:
from functions.eda import eda
import pandas as pd
url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv"
df = pd.read_csv(url)
eda(df)

=====DF Shape: (32403, 23)=====
***Numeric Columns***
player_id
	Num NA: 0
	% NA: 0.0%
	Min: 10
	Max: 1309800
	Range: 1309790
	25%: 106698.0
	75%: 524208.5
	St. Dev.: 280683.13989913743
	Num unique: 32403
last_season
	Num NA: 0
	% NA: 0.0%
	Min: 2012
	Max: 2024
	Range: 12
	25%: 2016.0
	75%: 2023.0
	St. Dev.: 3.965914065614276
	Num unique: 13
current_club_id
	Num NA: 0
	% NA: 0.0%
	Min: 3
	Max: 110302
	Range: 110299
	25%: 403.0
	75%: 3060.0
	St. Dev.: 11601.98297795499
	Num unique: 437
height_in_cm
	Num NA: 2344
	% NA: 7.233898095855322%
	Min: 17.0
	Max: 207.0
	Range: 190.0
	25%: 178.0
	75%: 187.0
	St. Dev.: 6.971224376399548
	Num unique: 52
market_value_in_eur
	Num NA: 1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
	25%: 100000.0
	75%: 700000.0
	St. Dev.: 6362017.247132119
	Num unique: 129
highest_market_value_in_eur
	Num NA: 1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
	25%: 275000.0
	75%: 2800000.0
	St. Dev.: 9653897.3865907
	Num unique: 206


***CATEGORICAL COLS***
first_name
	Num NA: 2058
	% NA: 6.351263771872976%
	Num Uniques: 6966
last_name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 23701
name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 31708
player_code
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 31667
country_of_birth
	Num NA: 2803
	% NA: 8.650433601826991%
	Num Uniques: 185
city_of_birth
	Num NA: 2461
	% NA: 7.5949757738481%
	Num Uniques: 8537
country_of_citizenship
	Num NA: 380
	% NA: 1.1727309199765454%
	Num Uniques: 183
date_of_birth
	Num NA: 47
	% NA: 0.14504829799709903%
	Num Uniques: 9272
sub_position
	Num NA: 185
	% NA: 0.5709347899885814%
	Num Uniques: 13
position
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 5
	Unique Vals: ['Attack' 'Goalkeeper' 'Defender' 'Midfield' 'Missing']
foot
	Num NA: 2593
	% NA: 8.002345461839953%
	Num Uniques: 3
	Unique Vals: ['right' 'left' nan 'both']
contract_expiration_date
	Num NA: 12131
	% NA: 37.43789155325124%
	Num Uniques: 114
agent_name
	Num NA: 16015
	% NA: 49.424436009011515%
	Num Uniques: 2833
image_url
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 26561
url
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 32403
current_club_domestic_competition_id
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 14
current_club_name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 437

In [9]:
# date_of_birth & height_in_cm
from scipy import stats
heights = df["height_in_cm"]
sk = stats.skew(heights, nan_policy="omit")
kurt = stats.kurtosis(heights, nan_policy="omit")
print(f"skew = {sk:.3f}; kurt = {kurt:.3f}")

skew = -1.775; kurt = 40.365

In [11]:
# IQR for outliers
q1 = heights.quantile(0.25)
q3 = heights.quantile(0.75)
iqr = q3 - q1
q1, q3, iqr

(np.float64(178.0), np.float64(187.0), np.float64(9.0))

In [18]:
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)
# df.loc[(df["height_in_cm"]<lower_bound) | (df["height_in_cm"]>upper_bound)]
hl = heights.loc[(heights<lower_bound) | (heights>upper_bound)].to_list()

In [19]:
def cm_to_ft(num):
    return (num * 0.393701) / 12
hl1 = [cm_to_ft(num) for num in hl]
hl1

[6.59449175,
 5.3805803333333335,
 6.725725416666667,
 5.21653825,
 5.3805803333333335,
 5.3805803333333335,
 5.2821550833333335,
 6.59449175,
 6.59449175,
 6.660108583333334,
 5.249346666666667,
 5.3805803333333335,
 6.7913422500000005,
 6.59449175,
 5.347771916666667,
 5.3149635,
 5.3805803333333335,
 5.347771916666667,
 6.660108583333334,
 5.3149635,
 5.3805803333333335,
 6.59449175,
 6.6929170000000004,
 6.59449175,
 6.59449175,
 5.3805803333333335,
 6.627300166666667,
 6.59449175,
 6.627300166666667,
 5.347771916666667,
 5.347771916666667,
 6.59449175,
 5.3149635,
 5.347771916666667,
 6.59449175,
 5.3805803333333335,
 5.3805803333333335,
 5.3805803333333335,
 5.347771916666667,
 5.3805803333333335,
 5.3805803333333335,
 5.3805803333333335,
 6.627300166666667,
 5.3805803333333335,
 5.3805803333333335,
 5.347771916666667,
 6.59449175,
 6.59449175,
 6.660108583333334,
 5.3805803333333335,
 5.347771916666667,
 5.3805803333333335,
 5.347771916666667,
 6.627300166666667,
 5.347771916666667,
 6.660108583333334,
 6.6929170000000004,
 6.660108583333334,
 6.59449175,
 6.59449175,
 6.660108583333334,
 5.21653825,
 5.347771916666667,
 6.627300166666667,
 6.59449175,
 6.660108583333334,
 5.249346666666667,
 5.3805803333333335,
 6.59449175,
 6.59449175,
 6.627300166666667,
 5.3149635,
 5.347771916666667,
 5.2821550833333335,
 6.660108583333334,
 5.347771916666667,
 6.59449175,
 6.627300166666667,
 5.3805803333333335,
 6.627300166666667,
 6.627300166666667,
 6.660108583333334,
 6.627300166666667,
 6.59449175,
 6.6929170000000004,
 6.627300166666667,
 5.3149635,
 6.758533833333334,
 6.59449175,
 6.660108583333334,
 6.725725416666667,
 6.6929170000000004,
 5.347771916666667,
 5.347771916666667,
 5.3805803333333335,
 6.59449175,
 5.3149635,
 6.59449175,
 6.627300166666667,
 5.3805803333333335,
 0.6233599166666667,
 5.3805803333333335,
 5.347771916666667,
 5.347771916666667,
 6.59449175,
 5.3805803333333335,
 0.5905515,
 6.627300166666667,
 5.249346666666667,
 5.3805803333333335,
 6.758533833333334,
 6.627300166666667,
 5.3805803333333335,
 0.5905515,
 5.3805803333333335,
 6.725725416666667,
 6.6929170000000004,
 6.6929170000000004,
 5.347771916666667,
 5.3805803333333335,
 5.347771916666667,
 5.3805803333333335,
 5.3805803333333335,
 5.347771916666667,
 6.758533833333334,
 5.3805803333333335,
 5.3149635,
 6.725725416666667,
 6.627300166666667,
 5.347771916666667,
 0.5577430833333333,
 5.2821550833333335,
 6.627300166666667,
 5.3805803333333335,
 6.6929170000000004,
 6.758533833333334,
 5.249346666666667,
 6.6929170000000004,
 5.3805803333333335,
 5.3805803333333335]

In [20]:
hl

[201.0,
 164.0,
 205.0,
 159.0,
 164.0,
 164.0,
 161.0,
 201.0,
 201.0,
 203.0,
 160.0,
 164.0,
 207.0,
 201.0,
 163.0,
 162.0,
 164.0,
 163.0,
 203.0,
 162.0,
 164.0,
 201.0,
 204.0,
 201.0,
 201.0,
 164.0,
 202.0,
 201.0,
 202.0,
 163.0,
 163.0,
 201.0,
 162.0,
 163.0,
 201.0,
 164.0,
 164.0,
 164.0,
 163.0,
 164.0,
 164.0,
 164.0,
 202.0,
 164.0,
 164.0,
 163.0,
 201.0,
 201.0,
 203.0,
 164.0,
 163.0,
 164.0,
 163.0,
 202.0,
 163.0,
 203.0,
 204.0,
 203.0,
 201.0,
 201.0,
 203.0,
 159.0,
 163.0,
 202.0,
 201.0,
 203.0,
 160.0,
 164.0,
 201.0,
 201.0,
 202.0,
 162.0,
 163.0,
 161.0,
 203.0,
 163.0,
 201.0,
 202.0,
 164.0,
 202.0,
 202.0,
 203.0,
 202.0,
 201.0,
 204.0,
 202.0,
 162.0,
 206.0,
 201.0,
 203.0,
 205.0,
 204.0,
 163.0,
 163.0,
 164.0,
 201.0,
 162.0,
 201.0,
 202.0,
 164.0,
 19.0,
 164.0,
 163.0,
 163.0,
 201.0,
 164.0,
 18.0,
 202.0,
 160.0,
 164.0,
 206.0,
 202.0,
 164.0,
 18.0,
 164.0,
 205.0,
 204.0,
 204.0,
 163.0,
 164.0,
 163.0,
 164.0,
 164.0,
 163.0,
 206.0,
 164.0,
 162.0,
 205.0,
 202.0,
 163.0,
 17.0,
 161.0,
 202.0,
 164.0,
 204.0,
 206.0,
 160.0,
 204.0,
 164.0,
 164.0]

In [22]:
(5*12) / 0.393701

152.39991770404444

In [ ]:
heights = heights.loc[heights > 150]
heights

0        184.0
1        190.0
4        194.0
7        179.0
8        193.0
         ...
32393    186.0
32394    175.0
32398    178.0
32399    180.0
32400    164.0
Name: height_in_cm, Length: 30055, dtype: float64

In [24]:
sk = stats.skew(heights, nan_policy="omit")
kurt = stats.kurtosis(heights, nan_policy="omit")
print(f"skew = {sk}; kurt = {kurt}")

skew = -0.046876795739341504; kurt = -0.3076357973086883

In [28]:
bm_df = df[["date_of_birth", "name", "position"]]

In [29]:

bm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32403 entries, 0 to 32402
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date_of_birth  32356 non-null  object
 1   name           32403 non-null  object
 2   position       32403 non-null  object
dtypes: object(3)
memory usage: 759.6+ KB

In [30]:
bm_df["date_of_birth"] = pd.to_datetime(bm_df["date_of_birth"])
bm_df.head()

C:\Users\michalewiczn\AppData\Local\Temp\ipykernel_3992\837312585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bm_df["date_of_birth"] = pd.to_datetime(bm_df["date_of_birth"])

  date_of_birth                name    position
0    1978-06-09      Miroslav Klose      Attack
1    1980-08-06  Roman Weidenfeller  Goalkeeper
2    1981-01-30    Dimitar Berbatov      Attack
3    1978-05-08               Lúcio    Defender
4    1981-03-18          Tom Starke  Goalkeeper

In [31]:
bm_df["month"] = bm_df["date_of_birth"].dt.month
bm_df

C:\Users\michalewiczn\AppData\Local\Temp\ipykernel_3992\1499764934.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bm_df["month"] = bm_df["date_of_birth"].dt.month

      date_of_birth                name    position  month
0        1978-06-09      Miroslav Klose      Attack    6.0
1        1980-08-06  Roman Weidenfeller  Goalkeeper    8.0
2        1981-01-30    Dimitar Berbatov      Attack    1.0
3        1978-05-08               Lúcio    Defender    5.0
4        1981-03-18          Tom Starke  Goalkeeper    3.0
...             ...                 ...         ...    ...
32398    2003-02-04           João Neto      Attack    2.0
32399    2007-09-06         Fábio Sambú      Attack    9.0
32400    2005-02-19      Hakim Sulemana      Attack    2.0
32401    2006-01-01     Diallo Sanoussi    Midfield    1.0
32402    2006-06-05        Issaka Seidu    Defender    6.0

[32403 rows x 4 columns]

In [32]:
sk = stats.skew(bm_df["month"], nan_policy="omit")
kurt = stats.kurtosis(bm_df["month"], nan_policy="omit")

sk, kurt

(np.float64(0.26205852205376656), np.float64(-1.1306173317984487))

In [36]:
months = bm_df["month"]
total = months.count()
md = {m:months.loc[months==m].count()/total for m in months.unique()}
md

{np.float64(6.0): np.float64(0.08020150822104093),
 np.float64(8.0): np.float64(0.07417480529113611),
 np.float64(1.0): np.float64(0.1256644826307331),
 np.float64(5.0): np.float64(0.09009148225985907),
 np.float64(3.0): np.float64(0.10433922610953146),
 np.float64(4.0): np.float64(0.09274941278279145),
 np.float64(11.0): np.float64(0.060977871183088145),
 np.float64(10.0): np.float64(0.06502657930522933),
 np.float64(nan): np.float64(0.0),
 np.float64(2.0): np.float64(0.10063048584497465),
 np.float64(7.0): np.float64(0.0783162319198912),
 np.float64(9.0): np.float64(0.0708987513907776),
 np.float64(12.0): np.float64(0.05692916306094697)}

In [ ]:
sorted(md.items())

[(np.float64(1.0), np.float64(0.1256644826307331)),
 (np.float64(2.0), np.float64(0.10063048584497465)),
 (np.float64(3.0), np.float64(0.10433922610953146)),
 (np.float64(4.0), np.float64(0.09274941278279145)),
 (np.float64(5.0), np.float64(0.09009148225985907)),
 (np.float64(6.0), np.float64(0.08020150822104093)),
 (np.float64(7.0), np.float64(0.0783162319198912)),
 (np.float64(8.0), np.float64(0.07417480529113611)),
 (np.float64(9.0), np.float64(0.0708987513907776)),
 (np.float64(10.0), np.float64(0.06502657930522933)),
 (np.float64(11.0), np.float64(0.060977871183088145)),
 (np.float64(nan), np.float64(0.0)),
 (np.float64(12.0), np.float64(0.05692916306094697))]